### PR TITLE
Update menu animation

### PR DESCRIPTION
**Pull request by MrWillCom**
This pull request updated the menu animation, and the `box-shadow`'s transition is smoother.

### CODE REVIEW

**Comment by yang991178** [comment]
Using width in transition causes weird behaviors that "squeeze" the contents. Additionally, clip-path provides a expansion animation.

**Comment by MrWillCom** [comment]
> Using width in transition causes weird behaviors that "squeeze" the contents. Additionally, clip-path provides a better expansion animation.

I've tested it recently, there's no error occured.

Here is the [record](https://github.com/yang991178/fluent-reader/files/5121631/test-record.zip).

**Comment by MrWillCom** [comment]
@yang991178 I'm sure this animation does **not** "squeeze" the contents.

**Comment by NoNamePro0** [comment]
Maybe just on macOS?

**Comment by MrWillCom** [comment]
> Maybe just on macOS?

I don't think that it is caused by different platforms. I've tested it on Windows.

I got width animation "squeezing" the contents because an `<nav>` element under menu's `overflow` property is `initial`, but the width of the icons of the menu items is fixed then there will be a scroll bar at the bottom of the `<nav>`. So I changed it to `hidden` and fixed some bugs caused by it. Now, it works well with the new realization without bugs.

**Comment by aeilot** [comment]
> Maybe just on macOS?

I have helped test it on macOS 10.15.6 (19G2021), which is the latest version. As @MrWillCom said, I think "this animation does not 'squeeze' the contents", but not really sure while I am not a front end engine2er.

[Here](https://github.com/aeilot/photo) is the record which is compressed to the 7z format. It's stored in a GitHub repo, and will be deleted in a month.

**Pull request closed without merging**
