### PR TITLE
Pause/resume updates for selected sources

### PR DESCRIPTION
**Pull request by tomaskikutis**
pause-updates

### CODE REVIEW

**Comment by yang991178** [comment]
Thanks for the PR. However, I personally don't know if this feature is useful enough to be included in the app as I can't think of a common use case for it. Also, it wouldn't make sense to pause updates on specific sources if that source is synced through an RSS service (since we just pull all new articles from the server instead of querying the individual sources in that case).

**Comment by tomaskikutis** [comment]
> However, I personally don't know if this feature is useful enough

I missed this feature coming from Thunderbird. I have sources that I don't want to follow very closely and always seeing their latest updates would be a distraction, but I still want to have them in the list of feeds and get updates manually when I want. I suspect it's a common case for people that have many feeds.

I agree with your comment about RSS services. Since I don't use them, I didn't look into that part of code and didn't know how they work. I could adjust the PR so the option is only available for local feeds. No problem if you decide not to merge it. I'll have it on my fork, so it's good enough for me :)

**Comment by yang991178** [comment]
I thought about adding a feature to hide a feed from all articles view in the past for a similar use case, and I may work on that in the future. Also FYI, there is an update interval limit feature in the app already, and adding an "infinite" value to the UI to the dropdown select in settings UI should achieve the same effect as this PR.

**Comment by tomaskikutis** [comment]
> Also FYI, there is an update interval limit feature in the app already, and adding an "infinite" value to the UI to the dropdown select in settings UI should achieve the same effect as this PR.

My main issue would be that it wouldn't be convenient and require too much clicks to do it. It would also not work to pause a source and maintain the existing fetch frequency after unpausing.

I'm closing the PR then, feel free to merge it in the future if you change your mind :)

**Pull request closed without merging**
